<?php

declare(strict_types=1);

namespace Drupal\license_service_subscriptions\Form;

use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\license_service_subscriptions\Service\SubscriptionChoiceTokenService;
use Drupal\license_service_subscriptions\Service\TierMigrationService;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Token-gated choose-plan form for subscribers on a deprecated plan.
 *
 * Route: /subscribe/choose/{token}
 *
 * The {token} path parameter is the raw 256-bit hex token generated by
 * SubscriptionChoiceTokenService::generate(). The form:
 *   - GET:  validates the token (UID-bound, not burned, not expired) and shows
 *     available active plans. If the token is invalid the page explains why.
 *   - POST: validates the token a second time, calls markIntentToChange() (which
 *     burns the token atomically with the intent row), then redirects to a
 *     confirmation page. NEVER auto-logs the user in via a token.
 *
 * Author: Jeremiah Buttler.
 */
class ChoosePlanForm extends FormBase {

  /**
   * Constructs a ChoosePlanForm.
   *
   * @param \Drupal\license_service_subscriptions\Service\SubscriptionChoiceTokenService $tokenService
   *   The choose-plan token service.
   * @param \Drupal\license_service_subscriptions\Service\TierMigrationService $migrationService
   *   The tier migration service.
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entityTypeManager
   *   The entity type manager.
   * @param \Drupal\Core\Database\Connection $database
   *   The database connection (reads intent row for context).
   * @param \Drupal\Core\Session\AccountProxyInterface $currentUser
   *   The current user.
   */
  public function __construct(
    protected readonly SubscriptionChoiceTokenService $tokenService,
    protected readonly TierMigrationService $migrationService,
    protected readonly EntityTypeManagerInterface $entityTypeManager,
    protected readonly Connection $database,
    protected readonly AccountProxyInterface $currentUser,
  ) {}

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container): static {
    return new static(
      $container->get('license_service_subscriptions.token'),
      $container->get('license_service_subscriptions.migration'),
      $container->get('entity_type.manager'),
      $container->get('database'),
      $container->get('current_user'),
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId(): string {
    return 'license_service_subscriptions_choose_plan';
  }

  /**
   * {@inheritdoc}
   *
   * @param array $form
   *   The form array.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The form state.
   * @param string $token
   *   The raw choose-plan token from the URL (injected by the route).
   */
  public function buildForm(array $form, FormStateInterface $form_state, string $token = ''): array {
    $uid = (int) $this->currentUser->id();

    // Store token in form state for use in submit.
    $form_state->set('_choose_plan_token', $token);

    // Validate the token on GET.
    if (!$this->tokenService->validate($token, $uid)) {
      $form['invalid'] = [
        '#type'   => 'item',
        '#markup' => '<div class="messages messages--error">' . $this->t(
          'This plan-selection link is invalid, has already been used, or has expired.
           Please contact support if you believe this is an error.'
        ) . '</div>',
      ];
      // Return early with no submit button.
      return $form;
    }

    // Load the intent row to get the subscription context.
    $tokenHash = hash('sha256', $token);
    $intent = $this->database->select('license_service_migration_intents', 'i')
      ->fields('i', ['uid', 'subscription_state_id', 'effective_at', 'token_expires'])
      ->condition('token_hash', $tokenHash)
      ->condition('token_used', 0)
      ->execute()
      ->fetchAssoc();

    if (!$intent) {
      // Should not reach here (validate() already checked), but be defensive.
      $form['invalid'] = [
        '#markup' => '<div class="messages messages--error">' . $this->t('Token lookup failed.') . '</div>',
      ];
      return $form;
    }

    // Load the subscription state row for context (current plan label, etc.).
    $stateRow = $this->database->select('license_service_subscriptions_state', 's')
      ->fields('s', ['plan_id', 'commerce_subscription_id'])
      ->condition('id', (int) $intent['subscription_state_id'])
      ->execute()
      ->fetchAssoc();

    $currentPlanId = $stateRow ? (string) $stateRow['plan_id'] : '';
    $commerceSubId = $stateRow ? (int) $stateRow['commerce_subscription_id'] : 0;
    $form_state->set('_commerce_sub_id', $commerceSubId);

    // Compute days remaining.
    $daysRemaining = max(0, (int) floor(((int) $intent['token_expires'] - time()) / 86400));

    $form['context'] = [
      '#type'   => 'item',
      '#markup' => '<div class="messages messages--warning">' . $this->t(
        'Your current plan (<strong>@plan</strong>) is being discontinued.
         Please choose a new plan below. This link expires in @days day(s).',
        ['@plan' => $currentPlanId, '@days' => $daysRemaining]
      ) . '</div>',
    ];

    // Build plan options from active, non-deprecated plans.
    $plans = $this->entityTypeManager
      ->getStorage('license_subscription_plan')
      ->loadMultiple();

    $planOptions = [];
    foreach ($plans as $planId => $plan) {
      if ($plan->isActive()) {
        $tierLabel = $plan->getTierId();
        $label = $plan->label() . ' (' . $tierLabel . ')';
        if ($plan->isPerpetual()) {
          $label .= ' — ' . $this->t('one-time');
        }
        $planOptions[(string) $planId] = $label;
      }
    }

    if (empty($planOptions)) {
      $form['no_plans'] = [
        '#markup' => '<div class="messages messages--warning">' . $this->t(
          'No alternative plans are currently available. The default fallback will be applied automatically.'
        ) . '</div>',
      ];

      $form['actions'] = ['#type' => 'actions'];
      $form['actions']['confirm_fallback'] = [
        '#type'  => 'submit',
        '#value' => $this->t('Confirm — apply default fallback'),
      ];
      $form_state->set('_target_plan_id', NULL);
      return $form;
    }

    $form['plan_id'] = [
      '#type'          => 'radios',
      '#title'         => $this->t('Choose your new plan'),
      '#options'       => $planOptions,
      '#required'      => TRUE,
      '#description'   => $this->t(
        'Your current subscription will continue until its period end, then switch
        to the plan you choose here. If the new plan is paid, you will need to
        complete checkout after confirming.'
      ),
    ];

    $form['actions'] = ['#type' => 'actions'];
    $form['actions']['submit'] = [
      '#type'  => 'submit',
      '#value' => $this->t('Confirm plan choice'),
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state): void {
    $token  = (string) ($form_state->get('_choose_plan_token') ?? '');
    $uid    = (int) $this->currentUser->id();

    // Re-validate the token at submit time to guard against race conditions.
    if (!$this->tokenService->validate($token, $uid)) {
      $form_state->setErrorByName(
        '',
        $this->t('The plan-selection link is no longer valid. It may have been used or expired.'),
      );
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state): void {
    $token         = (string) ($form_state->get('_choose_plan_token') ?? '');
    $commerceSubId = (int) ($form_state->get('_commerce_sub_id') ?? 0);
    $uid           = (int) $this->currentUser->id();
    $targetPlanId  = $form_state->getValue('plan_id') ?: NULL;

    try {
      $this->migrationService->markIntentToChange(
        $commerceSubId,
        $targetPlanId,
        $token,
        $uid,
      );

      $this->messenger()->addStatus(
        $this->t('Your plan choice has been recorded. You will receive a confirmation email with next steps.')
      );
    }
    catch (\Exception $e) {
      $this->messenger()->addError(
        $this->t('There was a problem recording your choice. Please try again or contact support.')
      );
      $this->getLogger('license_service_subscriptions')->error(
        'ChoosePlanForm submit failed: @msg',
        ['@msg' => $e->getMessage()],
      );
      return;
    }

    // Redirect to the front page (or a dedicated confirmation page in Phase 4).
    $form_state->setRedirect('<front>');
  }

}
